<?php

use Drupal\sc_sso_email_change_notifier\Event\UserUpdateEvent;

/**
 * Implements hook_form_alter().
 */
function sc_sso_email_change_notifier_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_form') {
    $form['actions']['submit']['#submit'][] = '_sc_sso_email_change_notifier_update_user_event';
  }
}


/**
 * Implements subscriber for user update action.
 */
function _sc_sso_email_change_notifier_update_user_event($form, $form_state) {
  if ($form["account"]["mail"]["#default_value"] !== $form_state->getUserInput()['mail']) {
    if (\Drupal::currentUser()->id() !== $form_state->get('user')->id()) {
      return;
    }
    $event = new UserUpdateEvent($form_state, $form);
    \Drupal::service('event_dispatcher')
      ->dispatch($event, UserUpdateEvent::EVENT_NAME);
  }
}

/**
 * Implements hook_mail().
 */
function sc_sso_email_change_notifier_mail($key, &$message, $params) {
  switch ($key) {
    case 'email-changing':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['label'];
      $message['body'][] = $params['message'];
      break;
  }
}
